### ISSUE TITLE
Planet hitbox

### ISSUE THREAD

**Issue by jvonhacht** [JohanKJIP/RocketKrieg#33]
Planet hitbox är ibland lite osync med texture. Vet inte hur man ska förbättra.

**Comment by SoFoDa** [comment]
Antar att det har och göra med att planetens hitbox är en oktogon vilket medför att skeppet inte förstörs på vissa ställen. Har inte varit ett allt för stort problem tidigare då planeterna alltid varit relativt små men nu när även stora planeter spawnas kan icke-cirkulära hitboxen vara mer påtaglig.
Kan göra den rundare.

**Comment by jvonhacht** [comment]
Jo förstod det också. Jag tror det skulle hjälpa om man på något sett kunde rendra hitboxen. Just nu är det svårt att se om den sitter rätt.

**Comment by jvonhacht** [comment]
Tycker det är helt okej för tillfället. Gjorde hitboxen lite mindre i förhållande till bilden.
