### ISSUE TITLE
Fire missiles with mouse?

### ISSUE THREAD

**Issue by jvonhacht** [JohanKJIP/RocketKrieg#74]
Just nu är det lite segt och onaturligt att skjuta raketer i den riktning man siktar i. Det slutar oftast med att man missar och åker baklänges för att skjuta aliens.

Vad tror du om att skjuta missiler där man siktar med musen?

**Comment by SoFoDa** [comment]
Kan testa att implementera detta. Vii får se vilket alternativ som våra speltestare föredrar. Kan eventuellt göra det möjligt att byta mellan sätten att skjuta i settings.

**Comment by jvonhacht** [comment]
Fixade detta. Tycker det blev lättare och roligare att spela.
