### ISSUE TITLE
Shield and boost component change

### ISSUE THREAD

**Issue by SoFoDa** [JohanKJIP/RocketKrieg#84]
When switching to another shield component, it does not get changed properly as it still has the same amount of charges as the last shield component for one round. After you die the amount of charges gets changed to the correct amount. The boost component should also get recharged between rounds.

**Comment by jvonhacht** [comment]
Det har med reloadPlayerstats att göra. Kan fixa det så fort det finns en new game och continue knapp i menyn. Tror reloadPlayerstats sitter i konstruktorn. Så när man går från en skräm t.ex. main menu eller game over menyn så laddar den in värdena skeppet hade när spelet stängdes ner eller avslutades. Kan kolla på det imorgon

**Comment by jvonhacht** [comment]
Fixat

**Comment by jvonhacht** [comment]
Nu är det fixat..
